#数据库配置
spring:
    datasource:
        name: ebus
        url: jdbc:mysql://10.1.254.76:3306/ebus?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
        username: dev
        password: 123456
        #使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver


#MyBatis配置
mybatis:
    type-aliases-package: com.lantaiyuan.ebus.model
    mapper-locations: classpath:mapping/*.xml

#kafka配置
kafka: 
  bootstrap: 
     servers:  10.1.20.111:9092
  #  servers:  202.104.136.228:9093 #202.104.136.228:2181
  session: 
    timeout-ms: 30000 
  auto-commit:
    enable: true
    interval-ms: 1000
  auto-offset: 
    reset: latest
  group: 
    id: relRouteBus
  topic: 
    city-code: gw2app-baoji:610300|gw2app-kaiping:440783
    jpushTopic: jpush
    od-topic: odPos
    virtulCardCodeTopic: LTY_TB_Req
    virtulCardCodeTopicResp: LTY_TB_Resp
    
#定时器配置
task: 
  #定时扫描lty_virtual_card_swipe_history，将未处理的记录转入到lty_virtual_card_expense_history
  dealWithUnCheckedSwipeRecord: 0 0/1 * * * ?
  # 定时扣款：虚拟公交卡未付费记录(1.一票制，2.分段制：上下车均已刷卡但未扣费，若遗漏下车刷卡的由另外的定时器处理)
  chargeUnpaidRecords: 0 0/1 * * * ?
  # 每天23点处理超时未刷第二次卡的分段收费记录
  dealWithOverTimeLadderRecord: 0 0 23 * * ?
  


#日志配置     
logging:
    level:
      root: INFO
      com:
        lantaiyuan:
          ebus:
            mapper: TRACE
      org: 
        springframework: 
          scheduling: INFO