#系统名
system:
  name: virtualCardSystem
#数据库配置
spring:
    #数据源配置
    datasource:
        name: ebus
        url: jdbc:mysql://10.1.254.76:3306/ebus?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
        username: dev
        password: 123456
        #使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    #redis配置
    redis:
        timeout: 60000
        database: 0
        port: 6379
        host: 10.1.254.80
        password:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

#MyBatis配置
mybatis:
    type-aliases-package: com.lantaiyuan.ebus.model
    mapper-locations: classpath:mapping/*.xml

#kafka配置
kafka: 
  bootstrap: 
     servers: 10.1.254.78:9092,10.1.254.84:9092,10.1.254.85:9092
  session: 
    timeout-ms: 30000 
  auto-commit:
    enable: true
    interval-ms: 1000
  auto-offset: 
    reset: latest
  group: 
    id: relRouteBus
  topic: 
    city-code: gw2app-baoji:610300|gw2app-kaiping:440783
    jpushTopic: jpush
    od-topic: odPos
    virtulCardCodeTopic: LTY_TB_Req
    virtulCardCodeTopicResp: LTY_TB_Resp
    
#定时器配置
task: 
  #定时扫描lty_virtual_card_swipe_history，将未处理的记录转入到lty_virtual_card_expense_history
  dealWithUnCheckedSwipeRecord: 0 0/1 * * * ?
  # 定时扣款：虚拟公交卡未付费记录(1.一票制，2.分段制：上下车均已刷卡但未扣费，若遗漏下车刷卡的由另外的定时器处理)
  chargeUnpaidRecords: 0 0/1 * * * ?
  # 每天23点处理超时未刷第二次卡的分段收费记录
  dealWithOverTimeLadderRecord: 0 0 23 * * ?

#日志配置     
logging:
    level:
      root: INFO
      com:
        lantaiyuan:
          ebus:
            mapper: TRACE
      org: 
        springframework: 
          scheduling: INFO

#zookeeper
zookeeper:
  serverPaths: 10.1.254.83:2181,10.1.254.87:2182,10.1.254.71:2183
  curator:
    baseSleepTimeMs: 1000
    maxRetries: 3

#线程池配置
threadPool:
  corePoolSize: 5
  maximumPoolSize: 10
  keepAliveTime: 0
  workQueueDefaultSize: 5

#单次线程处理数据个数
thread:
  handleSize: 10
  maxSize: 100
